### ISSUE TITLE
Minecraft crashes at the new world screen

### ISSUE THREAD

**Issue by Derpford** [dadobug1111/DadobugBedrockOres#4]
Stacktrace:
```
Reported exception thrown!
net.minecraft.ReportedException: mouseClicked event handler
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:535)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:85)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:118)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184)
	at MC-BOOTSTRAP/org.lwjgl.glfw/org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at MC-BOOTSTRAP/org.lwjgl/org.lwjgl.system.JNI.invokeV(Native Method)
	at MC-BOOTSTRAP/org.lwjgl.glfw/org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
	at TRANSFORMER/minecraft@1.18.2/com.mojang.blaze3d.systems.RenderSystem.m_69830_(RenderSystem.java:225)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1069)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.main.Main.main(Main.java:205)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.1.0/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
Caused by: java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:143)
	at TRANSFORMER/dadobugbedrockores@1.3.3/no.dadobug.BiomeSelectors.lambda$gensFeature$0(BiomeSelectors.java:36)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632)
	at TRANSFORMER/dadobugbedrockores@1.3.3/no.dadobug.BiomeSelectors.lambda$gensFeature$1(BiomeSelectors.java:34)
	at TRANSFORMER/architectury@4.2.50/dev.architectury.registry.level.biome.forge.BiomeModificationsImpl.modifyBiome(BiomeModificationsImpl.java:395)
	at TRANSFORMER/architectury@4.2.50/dev.architectury.registry.level.biome.forge.BiomeModificationsImpl.processAdditions(BiomeModificationsImpl.java:373)
	at net.minecraftforge.eventbus.ASMEventHandler_416_BiomeModificationsImpl_processAdditions_BiomeLoadingEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at TRANSFORMER/forge@40.1.0/net.minecraftforge.common.ForgeHooks.enhanceBiome(ForgeHooks.java:891)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.biome.Biome.lambda$static$6(Biome.java:51)
	at MC-BOOTSTRAP/datafixerupper@4.1.27/com.mojang.datafixers.util.Function6.lambda$null$4(Function6.java:18)
	at MC-BOOTSTRAP/datafixerupper@4.1.27/com.mojang.serialization.DataResult$Instance.ap3(DataResult.java:337)
	at MC-BOOTSTRAP/datafixerupper@4.1.27/com.mojang.serialization.codecs.RecordCodecBuilder$Instance$5.decode(RecordCodecBuilder.java:321)
	at MC-BOOTSTRAP/datafixerupper@4.1.27/com.mojang.serialization.codecs.RecordCodecBuilder$2.decode(RecordCodecBuilder.java:107)
	at MC-BOOTSTRAP/datafixerupper@4.1.27/com.mojang.serialization.MapDecoder.lambda$compressedDecode$0(MapDecoder.java:52)
	at MC-BOOTSTRAP/datafixerupper@4.1.27/com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138)
	at MC-BOOTSTRAP/datafixerupper@4.1.27/com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at MC-BOOTSTRAP/datafixerupper@4.1.27/com.mojang.serialization.DataResult.flatMap(DataResult.java:136)
	at MC-BOOTSTRAP/datafixerupper@4.1.27/com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52)
	at MC-BOOTSTRAP/datafixerupper@4.1.27/com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:91)
	at MC-BOOTSTRAP/datafixerupper@4.1.27/com.mojang.serialization.Decoder.parse(Decoder.java:18)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.resources.RegistryResourceAccess$InMemoryStorage.m_183313_(RegistryResourceAccess.java:144)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.resources.RegistryLoader.m_206767_(RegistryLoader.java:55)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.resources.RegistryLoader.m_206775_(RegistryLoader.java:37)
	at MC-BOOTSTRAP/datafixerupper@4.1.27/com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138)
	at MC-BOOTSTRAP/datafixerupper@4.1.27/com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at MC-BOOTSTRAP/datafixerupper@4.1.27/com.mojang.serialization.DataResult.flatMap(DataResult.java:136)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.resources.RegistryLoader.m_206762_(RegistryLoader.java:37)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.resources.RegistryLoader$Bound.m_206789_(RegistryLoader.java:91)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.core.RegistryAccess.m_206159_(RegistryAccess.java:295)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.core.RegistryAccess.m_206171_(RegistryAccess.java:290)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.resources.RegistryOps.m_206817_(RegistryOps.java:32)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.core.RegistryAccess.m_206197_(RegistryAccess.java:267)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.core.RegistryAccess.m_206215_(RegistryAccess.java:285)
	at MC-BOOTSTRAP/com.google.common@31.0.1-jre/com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.gui.screens.worldselection.CreateWorldScreen.m_205424_(CreateWorldScreen.java:108)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.gui.screens.worldselection.WorldSelectionList.m_101676_(WorldSelectionList.java:104)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.gui.screens.worldselection.WorldSelectionList.<init>(WorldSelectionList.java:85)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.gui.screens.worldselection.SelectWorldScreen.m_7856_(SelectWorldScreen.java:65)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.gui.screens.Screen.m_6575_(Screen.java:423)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.Minecraft.m_91152_(Minecraft.java:918)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.gui.screens.TitleScreen.lambda$addSingleplayerMultiplayerButtons$6(TitleScreen.java:254)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.gui.components.Button.m_5691_(Button.java:40)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.gui.components.AbstractButton.m_5716_(AbstractButton.java:16)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.gui.components.AbstractWidget.m_6375_(AbstractWidget.java:111)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.gui.components.events.ContainerEventHandler.m_6375_(ContainerEventHandler.java:27)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.gui.screens.TitleScreen.m_6375_(TitleScreen.java:534)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:88)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:528)
	... 24 more
```

**Comment by dadobug1111** [comment]
this shoud be fixed, just forgot to close the issue
